# Generated by Django 5.1.2 on 2024-10-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_courses_course_rename_usercourses_usercourse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
