# Generated by Django 5.1.2 on 2024-10-23 03:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Courses',
            new_name='Course',
        ),
        migrations.RenameModel(
            old_name='Usercourses',
            new_name='UserCourse',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='viedo',
            new_name='video',
        ),
    ]
